# Generated by Django 3.2.14 on 2022-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220909_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('height_over_sea', models.IntegerField(blank=True, default=0)),
                ('difficulty_level', models.CharField(choices=[('HARD', 'hard'), ('MEDIUM', 'medium'), ('EASY', 'easy')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='post',
            name='height_over_sea',
        ),
    ]
