# Generated by Django 3.2.14 on 2022-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220910_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HikeInformation',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(choices=[('HARD', 'hard'), ('MEDIUM', 'medium'), ('EASY', 'easy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='height_over_sea',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
