# Generated by Django 3.2.14 on 2022-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220910_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='city_name_of_place',
        ),
        migrations.AddField(
            model_name='post',
            name='best_season',
            field=models.CharField(blank=True, choices=[('1Q', 'January - Mars'), ('2Q', 'April - June'), ('3Q', 'July - September'), ('4Q', 'October - December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('HARD', 'hard'), ('MEDIUM', 'medium'), ('EASY', 'easy')], max_length=20, null=True),
        ),
    ]
