# Generated by Django 3.2.14 on 2022-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220910_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='best_season',
            field=models.CharField(blank=True, choices=[('January - Mars', 'January - Mars'), ('April - June', 'April - June'), ('July - September', 'July - September'), ('October - December', 'October - December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=20, null=True),
        ),
    ]
